[package]
name = "ad-usage"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
rayon.workspace = true
memchr.workspace = true
sha2.workspace = true
hex.workspace = true
ureq.workspace = true
iana-time-zone = "0.1"
toml_edit.workspace = true
rusqlite = { version = "0.40.2", features = ["bundled"] }
md-5 = "0.10"

[dev-dependencies]
tempfile.workspace = true
